<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Country extends Model
{
    use HasFactory, SoftDeletes;


    protected $guarded= [];

    protected $hidden = [
        'pivot'
    ];

    /**
     * @return void
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function($model){
            $model->uuid = Str::uuid()->toString();
        });
    }

    /**
     * @return bool
     */
    public function scopeHasAnyRelation(): bool
    {
        $relations = $this->getRelations();

        foreach ($relations as $relation) {
            if ($relation->count() > 0) {
                return true;
            }
        }
        return false;
    }

}
